language: csharp
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push /home/travis/build/sendgrid/csharp-http-client/*.nupkg -ApiKey
    $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
  on:
    branch: main
    tags: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: orpGfECBe6dSCCkitAIr7uoOYD/XAJnnWaPtOmMF42EO18KwuU1TCGVk3TpIlbEAU8e+iLc9lXdkSXmr5+aV4825fcux+OQ8LlRUWS88Xw37gS6JAj8HC5a0zUByt3+qmz5yW948nMs+iK2lPxTyymtOfMl89sYgbRYeGOH6zK37uHJXJtgD5QLgmNmmEXYWAxIMGzu0J9ZJyn5svLCd5+9CejAghR/NDP7E7ioca1CvDPB7HLQrRyvB0HBzS/ad/+PCciIg23scZFlMXdcE1Dqhgn8z6qyixw2sXjhu2fBOJy+kZIiDi4ZxbzCw3MMlcT98n7CSB/rEkAJgUBA4oeF6i9tjQt/JSEXwvQGi3cRfS79jtUePKeZFZOSYbq8sD4cFgA1vnRxAZ0jDB2yw2i+YVMSOrEig35KbV4H/SeQIgU64g3Rd7RQncemCcBi1TntBf4J7KO0wvmB1gGifL4MNCvdU0ZV2CHJ+O71l1xO4t91QWmTp5mFW1XF7SK0iL78mI8rG0bgfSSP2NTjWac7xLtoQBVrRK99HN988cYwM8cv3UwRBzYSrtQBEKWlDVr/sJRoRRHjYVPNhaNYVG8toxnoq1BzGuGtfjIMzctiFdIZRKOCutJZnvJ8nycaieWEmcJtFdxQsIXxYx1r6NgBV4C7v7jjIYsPtxKUpxR8=
